default: &default
  adapter: postgresql
  encoding: unicode
  host:     127.0.0.1
  port:     5432
  username: student
  password:
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: photogram_final_development

test:
  <<: *default
  database: photogram_final_test

production:
  <<: *default
  database: photogram_final_production
  username: photogram_final
  password: <%= ENV["PHOTOGRAM_FINAL_DATABASE_PASSWORD"] %>
